name: Update seats

on:
  push:
  schedule:
    - cron: '*/30 * * * *'

env:
  url: ${{ secrets.SUPABASE_URL }}
  key: ${{ secrets.SUPABASE_KEY }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Update seats
      run: python scraper.py